name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: build
      uses: actions/checkout@v2    
      run: make
      
    - name: Upload APK
      uses: actions/upload-artifact@v2-preview
      with:
        name: app
        path: dist/http_exporter
